### ISSUE TITLE
Tags, releases and Docker Images

### ISSUE THREAD

**Issue by shipilovds** [amnezia-vpn/amneziawg-exporter#2]

**Comment by shipilovds** [comment]
done

**Comment by shipilovds** [comment]
https://github.com/shipilovds/amneziawg-exporter/issues/2

**Comment by tiaga** [comment]
Let's avoid hardcode and start push Docker Images only if a semver tag was pushed to the repo. So, we should set the corresponding trigger:
```
on:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
```
and push only if tag was provided:
```
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: ${{ contains(github.ref, 'refs/tags/') }} # push if tag was set
```
